//this file is generated by program automatically,don't modify it!
#include "JsonView.h"
#include <string>
#include <sstream>
#include <map>
#include <vector>
#include <set>
using namespace std;

#include <json/json.h>
#include <iostream>
#include "Log.h"
#define CONTENT_TYPE CT_APPLICATION_JSON

IMPL_TROBJECT_CLASS(JsonView);
HttpResponse JsonView::genHttpResponse(const HttpViewData& JsonView_view_data)
{
	LOG4CPLUS_DEBUG(_logger, "gen json view");
	std::stringstream JsonView_tmp_stream;
Json::Value value=JsonView_view_data.get<Json::Value>("json");
Json::FastWriter writer;
JsonView_tmp_stream<<writer.write(value);
//std::cout<<writer.write(value);
	HttpResponse resp;
	resp.setStatusCode(HttpResponse::k200Ok);
#ifdef CONTENT_TYPE
	resp.setContentTypeCode(CONTENT_TYPE);
#else
	resp.setContentTypeCode(CT_TEXT_HTML);
#endif
	resp.setBody(JsonView_tmp_stream.str().c_str());
	return resp;
}
