//this file is generated by program automatically,don't modify it!
#include "HttpView.h"
class JsonView:public HttpView
{
public:
	JsonView(){};
	virtual ~JsonView(){};
	DECLARE_TROBJECT_CLASS(JsonView);
protected:
				virtual HttpResponse genHttpResponse(const HttpViewData&);
};